yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]  # Роутинг запросов приложения 'About'

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.create_comment, name='create_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),

]  # Роутинг запросов приложения Posts

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls')),
]

# Кастомные страницы ошибок
handler404 = 'core.views.page_not_found'
handler403 = settings.CSRF_FAILURE_VIEW

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db.models import UniqueConstraint, CheckConstraint
from django.db import models


class Group(models.Model):
    """ ORM модель групп """
    title = models.CharField('Название группы', max_length=200,
                             help_text='Дайте название группе')
    slug = models.SlugField('URL адрес', default='some string',
                            unique=True)
    description = models.TextField('Описание группы',
                                   max_length=10000,
                                   default='some string',
                                   help_text='Описание для группы')

    class Meta:
        """ Metaclass Group """
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'
        ordering = ('-title',)

    def __str__(self):
        return self.title


class Post(models.Model):
    """ ORM модель постов """
    text = models.TextField('Текст поста', max_length=15000,
                            help_text='Напишите что нибудь...')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True,
                                    db_index=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор', )
    group = models.ForeignKey(Group, blank=True, null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              verbose_name='Группа',
                              help_text='Группа поста')
    image = models.ImageField('Картинка',
                              upload_to='posts/',
                              blank=True,
                              null=True)

    class Meta:
        """ Metaclass Post """
        ordering = ('-pub_date',)
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[0:15]


class Comment(models.Model):
    """ ORM модель комментариев """
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор')
    text = models.TextField('Текст комментария',
                            max_length=10000,
                            help_text='Напишите что нибудь...')
    pub_date = models.DateTimeField('Дата публикации',
                                    auto_now_add=True)

    class Meta:
        """ Metaclass Comment """
        ordering = ('-pub_date',)
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return 'Комментарий от {}'.format(self.author)


class Follow(models.Model):
    """ ORM Following модель """
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        null=True
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        null=True
    )

    class Meta:
        """ Metaclass Follow """
        verbose_name = 'Лента'
        UniqueConstraint(fields=['author', 'user'],
                         name='re-subscription')
        CheckConstraint(
            name='prevent_self_follow',
            check=~models.Q(user=models.F('author')), )

    def __str__(self):
        return '{} подписан на {}'.format(self.user, self.author)

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """ Форма создание поста """

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Введите текст',
            'group': 'Выберите группу'
        }
        help_texts = {
            'text': 'Текст поста',
            'group': 'Название группы',
        }


class CommentForm(forms.ModelForm):
    """ Форма создание комментария """
    class Meta:
        model = Comment
        fields = ('text', )
    labels = {
        'text': 'Введите текст',
    }
    help_texts = {
        'text': 'Текст комментария',
    }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect

from .models import Follow, Group, Post, User
from .forms import CommentForm, PostForm
from .utils import paginator


def index(request):
    """ Главная страница """
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """ Страница группы """
    group_with_slug = get_object_or_404(Group, slug=slug)
    post_list = group_with_slug.posts.select_related('author').all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
        'group': group_with_slug,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """ Страница автора поста """
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group').all()
    page_obj = paginator(request, post_list)
    following = request.user.is_authenticated and author.following.filter(
        user=request.user).exists()
    context = {
        'page_obj': page_obj,
        'usermodel': author,
        'post_list': post_list,
        'following': following
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """ Подробное чтение поста """
    get_post = get_object_or_404(
        Post.objects.select_related('author').prefetch_related(
            'comments__author'), id=post_id)
    comment_form = CommentForm()
    context = {
        'onepost': get_post,
        'comments': get_post.comments.all(),
        'comment_form': comment_form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """ Функция создания поста """
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """ Редактирование поста """
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'post': post,
    }

    return render(request, 'posts/create_post.html', context)


@login_required
def create_comment(request, post_id):
    """ Добавление комментария """
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """ Все подписки пользователя """
    post_list = Post.objects.select_related(
        'author', 'group'
    ).filter(
        author__following__user=request.user
    )
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """ View подписки на автора """
    follow_author = get_object_or_404(User, username=username)
    if follow_author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=follow_author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """ View отписки на автора """
    get_object_or_404(Follow,
                      author__username=username,
                      ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/includes/comment_card.html
{% if user.is_authenticated %}
  <div class="form-group row my-3">
  <h6>Добавить комментарий...</h6>
  <form method="POST" action="{% url 'posts:create_comment' onepost.id %}">
    <div class="input-group">
    <textarea class="form-control" rows="3" method="POST" action="{% url 'posts:create_comment' onepost.id %}"
     {{ comment_form.text }}>
    </div>
    {% csrf_token %}
    <br>
    <button type="submit" class="btn btn-primary btn-lg">Добавить</button>
  </form>
  </div>
{% else %}
  <span style='color: red'>Войдите чтобы оставить комментарий...</span>
{% endif %}
{% for comment in comments %}
  <div class="comments" style="padding: 10px;">
    <p class="font-weight-bold">
        Комментарий от {{ comment.author }}
      <span class=" text-muted font-weight-normal">
        Дата публикации: {{ comment.pub_date }}
      </span>
    </p>
    {{ comment.text|linebreaksbr }}
  </div>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<!-- Шаблон Paginator -->
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/includes/postcard.html
 {% comment %} Карточка поста  {% endcomment %}
 {% load thumbnail %}
<article>
  <ul>
    <li>
      <a>
        Автор: {{ post.author }}
      </a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if not profile %}
      <li>
        <a  type="button" class="btn btn-primary btn-sm" href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
      </li>
    {% endif %}
  </ul>
  <p>
    {{ post.text|linebreaksbr }}
  </p>
  {% comment %} Загрузка изоброжения для поста {% endcomment %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <a  type="button" class="btn btn-primary btn-sm" href="{% url 'posts:post_detail' post.id %}">Подробно</a>
  {% if not group_page %}
    {% if post.group %}
      <a  type="button" class="btn btn-primary btn-sm" href="{% url 'posts:group_list' post.group.slug %}">
        Все записи группы
      </a>
    {% else %}
      <span  class="btn btn-default" style='color: red'>
        Этой публикации нет ни в одном сообществе.
      </span>
    {% endif %}
  {% endif %}
</article>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow_index %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}